export interface GeneratedScript {
  id: string;
  name: string;
  creatorPet: string;
  code: string;
  cronExpression?: string;
  createdAt: number;
}

export class ScriptGenerator {
  public generateScript(
    petName: string,
    scriptName: string,
    naturalLanguageInstruction: string,
    cron?: string
  ): GeneratedScript {
    const code = `#!/bin/bash
# Autogenerated script by PET ${petName}
# Instruction: ${naturalLanguageInstruction}
echo "[$(date)] Executando script '${scriptName}' criado por ${petName}..."
# Exemplo de comando gerado
termux-toast "PET ${petName}: ${scriptName} executado!"
`;

    return {
      id: `script_${Date.now()}`,
      name: scriptName,
      creatorPet: petName,
      code,
      cronExpression: cron,
      createdAt: Date.now()
    };
  }
}
